# Generated by Django 4.1 on 2022-11-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='quiz_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.quizanswer'),
        ),
    ]
