# Generated by Django 4.1 on 2022-11-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_account_quiz_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='quiz_answer',
        ),
    ]
