# Generated by Django 4.1 on 2022-11-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_account_quiz_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='nachname',
        ),
        migrations.AddField(
            model_name='account',
            name='vorname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
