# Generated by Django 4.1 on 2022-12-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notizen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notizen',
            options={'verbose_name_plural': 'Notizen'},
        ),
    ]
