# Generated by Django 4.1 on 2023-01-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_onboarding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Onboarding',
        ),
    ]
