# Generated by Django 4.1 on 2023-01-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seiten_id', models.IntegerField(default=-1)),
                ('seiten_titel', models.CharField(default='', max_length=150)),
                ('inhalt', models.TextField(default='', max_length=1000)),
                ('has_form', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Onboarding',
            },
        ),
    ]
