# Generated by Django 4.1 on 2022-12-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modul',
            options={'verbose_name_plural': 'Module'},
        ),
        migrations.CreateModel(
            name='Unterseite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30)),
                ('nummer', models.IntegerField(default=0)),
                ('modulname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.modul')),
            ],
            options={
                'verbose_name_plural': 'Unterseiten',
            },
        ),
    ]
