# Generated by Django 4.1 on 2022-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_alter_modul_options_unterseite'),
    ]

    operations = [
        migrations.AddField(
            model_name='unterseite',
            name='inhalt',
            field=models.TextField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
