# Generated by Django 4.1 on 2022-12-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_unterseite_inhalt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frage',
            old_name='frage_modul',
            new_name='modul',
        ),
        migrations.RenameField(
            model_name='unterseite',
            old_name='modulname',
            new_name='modul',
        ),
        migrations.AlterField(
            model_name='unterseite',
            name='titel',
            field=models.CharField(max_length=100),
        ),
    ]
