# Generated by Django 4.1 on 2022-12-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_rename_frage_modul_frage_modul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unterseite',
            name='naechste',
            field=models.IntegerField(default=-1),
        ),
    ]
