# Generated by Django 4.1 on 2023-01-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_unterseite_bild_beschreibung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unterseite',
            name='bild_beschreibung',
            field=models.CharField(default='', max_length=200),
        ),
    ]
