# Generated by Django 4.1 on 2023-01-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_alter_unterseite_bild_beschreibung'),
    ]

    operations = [
        migrations.AddField(
            model_name='unterseite',
            name='bild_quelle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
