# Generated by Django 3.1.7 on 2022-06-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage_satz', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=200)),
                ('nachname', models.CharField(max_length=200)),
                ('alter', models.DecimalField(decimal_places=0, max_digits=3)),
                ('email', models.EmailField(max_length=254)),
                ('befund', models.FileField(upload_to='uploads/{{Patient.nachname}}_{{Patient.vorname}}')),
            ],
        ),
        migrations.CreateModel(
            name='Antwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort_text', models.CharField(max_length=200)),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lernpfad.frage')),
            ],
        ),
    ]
