# Generated by Django 3.1.7 on 2022-06-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='frage',
            name='frage_modul',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lernpfad.modul'),
            preserve_default=False,
        ),
    ]
