# Generated by Django 3.1.7 on 2022-06-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0002_auto_20220610_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='antwort',
            name='erklaerung',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antwort',
            name='richtige_loesung',
            field=models.BooleanField(default=False),
        ),
    ]
