# Generated by Django 4.1 on 2022-11-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0002_modul_frage_antwort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frage',
            name='frage_modul',
        ),
        migrations.DeleteModel(
            name='Antwort',
        ),
        migrations.DeleteModel(
            name='Frage',
        ),
        migrations.DeleteModel(
            name='Modul',
        ),
    ]
