# Generated by Django 3.1.7 on 2022-06-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0004_auto_20220610_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antwort',
            name='erklaerung',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
