# Generated by Django 3.1.7 on 2022-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0005_auto_20220610_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='alter',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='befund',
            field=models.FileField(blank=True, upload_to='uploads/{{Patient.nachname}}_{{Patient.vorname}}'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
