# Generated by Django 3.1.7 on 2022-06-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0006_auto_20220613_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='alter',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
