# Generated by Django 3.1.7 on 2022-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0007_auto_20220613_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lernpfad_abgeschlossen',
            field=models.BooleanField(default=False),
        ),
    ]
