# Generated by Django 3.1.7 on 2022-06-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0009_auto_20220629_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_id',
            field=models.CharField(default='', max_length=6),
        ),
    ]
