# Generated by Django 3.1.7 on 2022-07-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0010_patient_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='antwort41',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='antwort42',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='antwort43',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='antwort44',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='antwort45',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='feedback',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fragen',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
