# Generated by Django 3.1.7 on 2022-07-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0011_auto_20220706_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='antwort41',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='antwort42',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='antwort43',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='antwort44',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='antwort45',
        ),
    ]
