# Generated by Django 3.1.7 on 2022-07-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0012_auto_20220706_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antwort',
            options={'verbose_name_plural': 'antworten'},
        ),
        migrations.AlterModelOptions(
            name='frage',
            options={'verbose_name_plural': 'fragen'},
        ),
        migrations.AlterModelOptions(
            name='modul',
            options={'verbose_name_plural': 'module'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'patienten'},
        ),
        migrations.AddField(
            model_name='frage',
            name='frage_id',
            field=models.CharField(default='', max_length=6),
        ),
    ]
