# Generated by Django 3.1.7 on 2022-07-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0013_auto_20220706_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frage',
            name='frage_id',
        ),
        migrations.AddField(
            model_name='frage',
            name='frage_reihenfolge',
            field=models.CharField(default='1', max_length=6),
        ),
    ]
