# Generated by Django 3.1.7 on 2022-07-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0014_auto_20220706_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frage',
            name='frage_reihenfolge',
        ),
        migrations.AddField(
            model_name='antwort',
            name='antwort_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frage',
            name='frage_id',
            field=models.IntegerField(default=0),
        ),
    ]
