# Generated by Django 3.1.7 on 2022-07-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0016_auto_20220706_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='eigenständigkeitserklärung',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='antwort',
            name='antwort_text',
            field=models.TextField(max_length=200),
        ),
    ]
