# Generated by Django 4.1 on 2022-11-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0017_auto_20220706_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='geburtsdatum',
            field=models.CharField(default='', max_length=10),
        ),
    ]
