# Generated by Django 4.1 on 2022-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0018_patient_geburtsdatum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='alter',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='befund',
        ),
        migrations.AlterField(
            model_name='patient',
            name='geburtsdatum',
            field=models.DateField(blank=True, editable=False),
        ),
    ]
