# Generated by Django 4.1 on 2022-11-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0019_remove_patient_alter_remove_patient_befund_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='geburtsdatum',
        ),
    ]
