# Generated by Django 4.1 on 2022-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0020_remove_patient_geburtsdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='geburtsdatum',
            field=models.DateField(auto_now=True),
        ),
    ]
