# Generated by Django 4.1 on 2022-11-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0022_patient_blub'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='nummer',
            field=models.IntegerField(default=0),
        ),
    ]
