# Generated by Django 4.1 on 2022-11-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0023_modul_nummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='frage',
            name='frage_titel',
            field=models.CharField(default='', max_length=200),
        ),
    ]
