# Generated by Django 4.1 on 2022-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0024_frage_frage_titel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antwort',
            name='erklaerung',
        ),
        migrations.AddField(
            model_name='frage',
            name='erklaerung',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
