# Generated by Django 4.1 on 2022-11-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernpfad', '0025_remove_antwort_erklaerung_frage_erklaerung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blub',
        ),
        migrations.AlterField(
            model_name='frage',
            name='frage_satz',
            field=models.TextField(max_length=200),
        ),
    ]
